import { Link } from "react-router-dom";
import { Search, Upload, Brain, FileText, Zap, Shield, ArrowRight, Sparkles } from "lucide-react";
import { motion } from "framer-motion";

const features = [
  {
    icon: Sparkles,
    title: "AI-Powered Answers",
    description: "Get intelligent, context-aware answers generated by advanced AI models using your document content.",
    gradient: "from-cyan-500 to-cyan-600",
  },
  {
    icon: Search,
    title: "Semantic Search",
    description: "Find information using natural language queries. No keywords needed — just ask like you'd ask a colleague.",
    gradient: "from-violet-500 to-violet-600",
  },
  {
    icon: Shield,
    title: "Source Attribution",
    description: "Every answer comes with exact source citations — document name and page number for full traceability.",
    gradient: "from-cyan-500 to-violet-500",
  },
];

const stats = [
  { label: "Response Time", value: "< 3s" },
  { label: "Accuracy", value: "95%+" },
  { label: "LLM Models", value: "100+" },
];

export default function Landing() {
  return (
    <div className="relative overflow-hidden">
      {/* Ambient Glow Orbs */}
      <div className="pointer-events-none absolute inset-0">
        <div className="absolute -top-40 left-1/4 h-[500px] w-[500px] rounded-full bg-cyan-500/[0.07] blur-[120px]" />
        <div className="absolute -bottom-40 right-1/4 h-[500px] w-[500px] rounded-full bg-violet-500/[0.07] blur-[120px]" />
        <div className="absolute top-1/3 right-1/3 h-[300px] w-[300px] rounded-full bg-cyan-500/[0.04] blur-[100px]" />
      </div>

      {/* Hero Section */}
      <section className="relative z-10 mx-auto max-w-7xl px-4 pt-16 pb-24 sm:px-6 lg:px-8">
        <div className="flex flex-col items-center text-center lg:flex-row lg:text-left lg:items-start lg:gap-16">
          {/* Left — Text */}
          <motion.div
            className="flex-1 max-w-2xl"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <div className="mb-4 inline-flex items-center gap-2 rounded-full glass-panel px-4 py-1.5 text-xs font-medium text-cyan-400">
              <Zap className="h-3.5 w-3.5" />
              Powered by RAG + GPT-4o-mini
            </div>

            <h1 className="text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl">
              <span className="gradient-text">Unlock the Intelligence</span>
              <br />
              <span className="text-foreground">Inside Your Documents</span>
            </h1>

            <p className="mt-6 text-lg text-muted-foreground leading-relaxed max-w-xl">
              Upload PDFs, ask questions in natural language, and get AI-powered answers with exact source citations.
              Built for students, researchers, and project teams.
            </p>

            <div className="mt-8 flex flex-col sm:flex-row gap-4">
              <Link
                to="/"
                className="inline-flex items-center justify-center gap-2 rounded-xl btn-gradient px-8 py-3.5 text-sm font-semibold"
              >
                <Search className="h-4 w-4" />
                Start Searching
                <ArrowRight className="h-4 w-4" />
              </Link>
              <Link
                to="/upload"
                className="inline-flex items-center justify-center gap-2 rounded-xl btn-gradient-outline px-8 py-3.5 text-sm font-semibold"
              >
                <Upload className="h-4 w-4" />
                Upload PDFs
              </Link>
            </div>

            {/* Stats */}
            <div className="mt-12 flex gap-8">
              {stats.map((stat) => (
                <div key={stat.label}>
                  <p className="text-2xl font-bold gradient-text">{stat.value}</p>
                  <p className="text-xs text-muted-foreground mt-1">{stat.label}</p>
                </div>
              ))}
            </div>
          </motion.div>

          {/* Right — 3D Illustration */}
          <motion.div
            className="flex-1 flex justify-center mt-12 lg:mt-0"
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.7, delay: 0.2 }}
          >
            <div className="relative w-80 h-80 lg:w-[420px] lg:h-[420px]">
              {/* Orbiting ring */}
              <div className="absolute inset-0 rounded-full border border-cyan-500/20 animate-spin-slow" />
              <div className="absolute inset-4 rounded-full border border-violet-500/15 animate-spin-slow" style={{ animationDirection: 'reverse', animationDuration: '30s' }} />

              {/* Center Brain */}
              <div className="absolute inset-0 flex items-center justify-center">
                <div className="relative">
                  <div className="absolute -inset-8 rounded-full bg-gradient-to-br from-cyan-500/20 to-violet-500/20 blur-2xl animate-pulse" />
                  <div className="relative flex h-24 w-24 items-center justify-center rounded-3xl bg-gradient-to-br from-cyan-500 to-violet-500 shadow-glow-cyan">
                    <Brain className="h-12 w-12 text-white" />
                  </div>
                </div>
              </div>

              {/* Floating Document Cards */}
              {[
                { top: '10%', left: '5%', delay: 0, name: 'Report.pdf' },
                { top: '5%', right: '10%', delay: 1, name: 'Research.pdf' },
                { bottom: '15%', left: '0%', delay: 2, name: 'Manual.pdf' },
                { bottom: '10%', right: '5%', delay: 0.5, name: 'Analysis.pdf' },
              ].map((card, i) => (
                <motion.div
                  key={i}
                  className="absolute glass-card rounded-xl px-3 py-2 flex items-center gap-2"
                  style={{ top: card.top, left: card.left, right: card.right, bottom: card.bottom } as React.CSSProperties}
                  animate={{ y: [0, -8, 0] }}
                  transition={{ duration: 4, repeat: Infinity, delay: card.delay, ease: "easeInOut" }}
                >
                  <FileText className="h-4 w-4 text-cyan-400" />
                  <span className="text-xs text-foreground/80">{card.name}</span>
                </motion.div>
              ))}

              {/* Scanning Beam */}
              <motion.div
                className="absolute left-1/2 top-1/2 -translate-x-1/2 h-0.5 w-48 origin-left"
                style={{ background: 'linear-gradient(90deg, rgba(6,182,212,0.6), transparent)' }}
                animate={{ rotate: [0, 360] }}
                transition={{ duration: 8, repeat: Infinity, ease: "linear" }}
              />
            </div>
          </motion.div>
        </div>
      </section>

      {/* Feature Cards */}
      <section className="relative z-10 mx-auto max-w-7xl px-4 pb-24 sm:px-6 lg:px-8">
        <motion.div
          className="text-center mb-12"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          <h2 className="text-3xl font-bold gradient-text">How It Works</h2>
          <p className="mt-3 text-muted-foreground">
            Three simple steps to unlock intelligence from your documents
          </p>
        </motion.div>

        <div className="grid gap-6 md:grid-cols-3">
          {features.map((feature, index) => (
            <motion.div
              key={feature.title}
              className="glass-card card-3d rounded-2xl p-8"
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: index * 0.15 }}
            >
              <div className={`inline-flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br ${feature.gradient} mb-5 shadow-lg`}>
                <feature.icon className="h-6 w-6 text-white" />
              </div>
              <h3 className="text-lg font-semibold text-foreground mb-2">{feature.title}</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">{feature.description}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Pipeline Section */}
      <section className="relative z-10 mx-auto max-w-5xl px-4 pb-24 sm:px-6 lg:px-8">
        <motion.div
          className="glass-card rounded-2xl p-8 md:p-12"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          <h3 className="text-2xl font-bold gradient-text mb-8 text-center">Processing Pipeline</h3>
          <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
            {[
              { step: "1", label: "Upload PDF", icon: Upload },
              { step: "2", label: "Extract Text", icon: FileText },
              { step: "3", label: "Vectorize", icon: Zap },
              { step: "4", label: "Semantic Search", icon: Search },
              { step: "5", label: "AI Answer", icon: Sparkles },
            ].map((item, i) => (
              <motion.div
                key={item.step}
                className="flex flex-col items-center text-center"
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.1 }}
              >
                <div className="flex h-14 w-14 items-center justify-center rounded-2xl glass-panel mb-3 hover-lift">
                  <item.icon className="h-6 w-6 text-cyan-400" />
                </div>
                <span className="text-xs font-medium text-foreground">{item.label}</span>
                <span className="text-[10px] text-muted-foreground mt-1">Step {item.step}</span>
              </motion.div>
            ))}
          </div>
        </motion.div>
      </section>
    </div>
  );
}
